#!/bin/sh

if [ $# -lt 2 ]
then
  echo "usage: basename source" 1>&2
  exit 1
fi

CC_PICFLAG=`head -n 1 conf-picflag`
if [ $? -ne 0 ]
then
  echo "fatal: could not read conf-picflag" 1>&2
  exit 1
fi

exec ./cc $1 $2 ${CC_PICFLAG}
