#!/bin/sh

fatal()
{
  echo "fatal: $1" 1>&2
  exit 1
}

tmpdir="/tmp"
repos="file:///source"

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
then
  echo "usage: [group/proj] [tag] [outname]"
  echo "  example: coreland/corelib CORELIB-0_3 corelib-0.3"
  exit 1
fi

in_prog="$1"
tag="$2"
outname="$3"

# parse

group=`echo ${in_prog} | awk -F/ '{print $1}'`
prog=`echo ${in_prog} | awk -F/ '{print $2}'`
pwd=`pwd`

if [ ! -d RELEASE ]
then
  mkdir RELEASE
  if [ $? -ne 0 ]; then fatal "could not create RELEASE directory"; fi
fi

# retrieval

cd ${tmpdir}
if [ $? -ne 0 ]; then fatal "couldn't cd to ${tmpdir}"; fi

svn export -r HEAD ${repos}/${group}/${prog}/tags/${tag} ${outname}
if [ $? -ne 0 ]; then fatal "couldn't retrieve from svn"; fi

# packaging

tar cf - ${outname} | bzip2 -9 > ${pwd}/RELEASE/${outname}.tar.bz2
if [ $? -ne 0 ]; then fatal "error creating package"; fi

sha256 ${pwd}/RELEASE/${outname}.tar.bz2 > ${pwd}/RELEASE/${outname}.tar.bz2.sha
if [ $? -ne 0 ]; then fatal "error creating sha256 checksum"; fi
